#!/bin/bash

echo -n './, ../, '

ls -A --quoting-style=shell-escape | sort -k1,1 -t '_' | while read -r line; do
    if [[ -d "$line" ]]; then
        echo -n "${line}/, "
    else
        echo -n "${line}, "
    fi
done | sed 's/, $/\n/'
